// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iMgAMijvcRndpQj_LKPYlj4kENXas5Y',
    appId: '1:639770175858:web:128cc384cf8d21010b15eb',
    messagingSenderId: '639770175858',
    projectId: 'reverb-2025',
    authDomain: 'reverb-2025.firebaseapp.com',
    storageBucket: 'reverb-2025.firebasestorage.app',
    measurementId: 'G-N5SM04GD4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpmIqOXLQDkPudNZ34Qqy8FStav8hYWg',
    appId: '1:639770175858:android:86605d0153e104cf0b15eb',
    messagingSenderId: '639770175858',
    projectId: 'reverb-2025',
    storageBucket: 'reverb-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD46oykj6oe4R31IAtKaI_23WNII18kvvk',
    appId: '1:639770175858:ios:ebffe557ae77745e0b15eb',
    messagingSenderId: '639770175858',
    projectId: 'reverb-2025',
    storageBucket: 'reverb-2025.firebasestorage.app',
    iosBundleId: 'com.example.reverb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD46oykj6oe4R31IAtKaI_23WNII18kvvk',
    appId: '1:639770175858:ios:ebffe557ae77745e0b15eb',
    messagingSenderId: '639770175858',
    projectId: 'reverb-2025',
    storageBucket: 'reverb-2025.firebasestorage.app',
    iosBundleId: 'com.example.reverb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1iMgAMijvcRndpQj_LKPYlj4kENXas5Y',
    appId: '1:639770175858:web:1a695b734148d3f50b15eb',
    messagingSenderId: '639770175858',
    projectId: 'reverb-2025',
    authDomain: 'reverb-2025.firebaseapp.com',
    storageBucket: 'reverb-2025.firebasestorage.app',
    measurementId: 'G-58EHY8SK6S',
  );
}
